// Sorteamos os gols de cada time nas rodadas, com um limite de até 5 gols, 
// para (tentarmos) ser o mais realista possível.

const x = 6 // X representa o número máximo de gols + 1 (pois o math.floor arredonda sempre para baixo)

// Rodadas grupo A:
export var grupoAtime1r1 = Math.floor(Math.random()*x)
export var grupoAtime1r2 = Math.floor(Math.random()*x)
export var grupoAtime1r3 = Math.floor(Math.random()*x)
export var grupoAtime2r1 = Math.floor(Math.random()*x)
export var grupoAtime2r2 = Math.floor(Math.random()*x)
export var grupoAtime2r3 = Math.floor(Math.random()*x)
export var grupoAtime3r1 = Math.floor(Math.random()*x)
export var grupoAtime3r2 = Math.floor(Math.random()*x)
export var grupoAtime3r3 = Math.floor(Math.random()*x)
export var grupoAtime4r1 = Math.floor(Math.random()*x)
export var grupoAtime4r2 = Math.floor(Math.random()*x)
export var grupoAtime4r3 = Math.floor(Math.random()*x)
//Rodadas grupo B:
export var grupoBtime1r1 = Math.floor(Math.random()*x)
export var grupoBtime1r2 = Math.floor(Math.random()*x)
export var grupoBtime1r3 = Math.floor(Math.random()*x)
export var grupoBtime2r1 = Math.floor(Math.random()*x)
export var grupoBtime2r2 = Math.floor(Math.random()*x)
export var grupoBtime2r3 = Math.floor(Math.random()*x)
export var grupoBtime3r1 = Math.floor(Math.random()*x)
export var grupoBtime3r2 = Math.floor(Math.random()*x)
export var grupoBtime3r3 = Math.floor(Math.random()*x)
export var grupoBtime4r1 = Math.floor(Math.random()*x)
export var grupoBtime4r2 = Math.floor(Math.random()*x)
export var grupoBtime4r3 = Math.floor(Math.random()*x)

//Rodadas grupo C:
export var grupoCtime1r1 = Math.floor(Math.random()*x)
export var grupoCtime1r2 = Math.floor(Math.random()*x)
export var grupoCtime1r3 = Math.floor(Math.random()*x)
export var grupoCtime2r1 = Math.floor(Math.random()*x)
export var grupoCtime2r2 = Math.floor(Math.random()*x)
export var grupoCtime2r3 = Math.floor(Math.random()*x)
export var grupoCtime3r1 = Math.floor(Math.random()*x)
export var grupoCtime3r2 = Math.floor(Math.random()*x)
export var grupoCtime3r3 = Math.floor(Math.random()*x)
export var grupoCtime4r1 = Math.floor(Math.random()*x)
export var grupoCtime4r2 = Math.floor(Math.random()*x)
export var grupoCtime4r3 = Math.floor(Math.random()*x)

//Rodadas grupo D:
export var grupoDtime1r1 = Math.floor(Math.random()*x)
export var grupoDtime1r2 = Math.floor(Math.random()*x)
export var grupoDtime1r3 = Math.floor(Math.random()*x)
export var grupoDtime2r1 = Math.floor(Math.random()*x)
export var grupoDtime2r2 = Math.floor(Math.random()*x)
export var grupoDtime2r3 = Math.floor(Math.random()*x)
export var grupoDtime3r1 = Math.floor(Math.random()*x)
export var grupoDtime3r2 = Math.floor(Math.random()*x)
export var grupoDtime3r3 = Math.floor(Math.random()*x)
export var grupoDtime4r1 = Math.floor(Math.random()*x)
export var grupoDtime4r2 = Math.floor(Math.random()*x)
export var grupoDtime4r3 = Math.floor(Math.random()*x)

//Rodadas grupo E:
export var grupoEtime1r1 = Math.floor(Math.random()*x)
export var grupoEtime1r2 = Math.floor(Math.random()*x)
export var grupoEtime1r3 = Math.floor(Math.random()*x)
export var grupoEtime2r1 = Math.floor(Math.random()*x)
export var grupoEtime2r2 = Math.floor(Math.random()*x)
export var grupoEtime2r3 = Math.floor(Math.random()*x)
export var grupoEtime3r1 = Math.floor(Math.random()*x)
export var grupoEtime3r2 = Math.floor(Math.random()*x)
export var grupoEtime3r3 = Math.floor(Math.random()*x)
export var grupoEtime4r1 = Math.floor(Math.random()*x)
export var grupoEtime4r2 = Math.floor(Math.random()*x)
export var grupoEtime4r3 = Math.floor(Math.random()*x)

//Rodadas grupo F:
export var grupoFtime1r1 = Math.floor(Math.random()*x)
export var grupoFtime1r2 = Math.floor(Math.random()*x)
export var grupoFtime1r3 = Math.floor(Math.random()*x)
export var grupoFtime2r1 = Math.floor(Math.random()*x)
export var grupoFtime2r2 = Math.floor(Math.random()*x)
export var grupoFtime2r3 = Math.floor(Math.random()*x)
export var grupoFtime3r1 = Math.floor(Math.random()*x)
export var grupoFtime3r2 = Math.floor(Math.random()*x)
export var grupoFtime3r3 = Math.floor(Math.random()*x)
export var grupoFtime4r1 = Math.floor(Math.random()*x)
export var grupoFtime4r2 = Math.floor(Math.random()*x)
export var grupoFtime4r3 = Math.floor(Math.random()*x)
//Rodadas grupo G:
export var grupoGtime1r1 = Math.floor(Math.random()*x)
export var grupoGtime1r2 = Math.floor(Math.random()*x)
export var grupoGtime1r3 = Math.floor(Math.random()*x)
export var grupoGtime2r1 = Math.floor(Math.random()*x)
export var grupoGtime2r2 = Math.floor(Math.random()*x)
export var grupoGtime2r3 = Math.floor(Math.random()*x)
export var grupoGtime3r1 = Math.floor(Math.random()*x)
export var grupoGtime3r2 = Math.floor(Math.random()*x)
export var grupoGtime3r3 = Math.floor(Math.random()*x)
export var grupoGtime4r1 = Math.floor(Math.random()*x)
export var grupoGtime4r2 = Math.floor(Math.random()*x)
export var grupoGtime4r3 = Math.floor(Math.random()*x)

//Rodadas grupo H:
export var grupoHtime1r1 = Math.floor(Math.random()*x)
export var grupoHtime1r2 = Math.floor(Math.random()*x)
export var grupoHtime1r3 = Math.floor(Math.random()*x)
export var grupoHtime2r1 = Math.floor(Math.random()*x)
export var grupoHtime2r2 = Math.floor(Math.random()*x)
export var grupoHtime2r3 = Math.floor(Math.random()*x)
export var grupoHtime3r1 = Math.floor(Math.random()*x)
export var grupoHtime3r2 = Math.floor(Math.random()*x)
export var grupoHtime3r3 = Math.floor(Math.random()*x)
export var grupoHtime4r1 = Math.floor(Math.random()*x)
export var grupoHtime4r2 = Math.floor(Math.random()*x)
export var grupoHtime4r3 = Math.floor(Math.random()*x)